<<PRES_OR_HANDOUTS, cache=FALSE, echo=FALSE, include=TRUE, results='asis'>>=
if(!exists("HANDOUT")) HANDOUT <- FALSE
if(HANDOUT){
   cat("
\\documentclass[handout]{beamer}
\\usepackage{pgf,pgfpages}
\\pgfpagesuselayout{4 on 1}[letterpaper,landscape,border shrink=0.5in]
")
} else {
   cat("\\documentclass{beamer}")
}
rm(HANDOUT)
@

\usepackage{beamerthemeclassic}
\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage{multicol}

\newcommand{\plot}{0.42}
\newcommand{\pr}{\mathbf{Prob}}
\newcommand{\el}{\mbox{\;or\;}}
\newcommand{\rymd}{\vspace{0.3cm}}

%\setbeamersize{text margin left=6mm, text margin right=2mm}  % DEFAULT
\setbeamersize{text margin left=3mm, text margin right=2mm}

\title{Introduction to Biostatistics \\ Lecture 9A}
\author{Henrik Renlund}
\date{2014-10-16}

<<cache=FALSE, echo=FALSE, include=FALSE>>=
.yellow <- wes.palette(5, "Cavalcanti")[1]
.green <- wes.palette(5, "Cavalcanti")[2]
.grey <- wes.palette(5, "Cavalcanti")[3]
.blue <- wes.palette(5, "Cavalcanti")[4]
.red <- wes.palette(5, "Cavalcanti")[5]
.seq3 <- brewer.pal(5,"YlGn")[2:4]
@


\begin{document} % >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

% \frame{ % -------------------------------------------------------------------->
% \begin{center}
% \includegraphics[scale=0.34]{pics/frequentists_vs_bayesians.png}
% \end{center}
% }
\frame{ % -------------------------------------------------------------------->
\titlepage
\begin{center}
\includegraphics[scale=0.8]{pics/ucrlogo.pdf}
\end{center}
}
% \frame{ % -------------------------------------------------------------------->
% \frametitle{Contents of Lecture 1-2}
% \tableofcontents
% }
\frame{ % -------------------------------------------------------------------->
\frametitle{What shall we learn today?}

The concept of (statistical) 'power' and its relation to  sample size calculations.

We will briefly discuss resampling techiques (bootstrap).
% We will (briefly) discuss  problems and solutions in interpreting
% positive and negative results.
%
% \begin{itemize}
% \item How to design studies to make null results interesting.
% \item Factors that can make statistically significant results misleading.
% \end{itemize}
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section[Power]{Power} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<power, cache=FALSE>>=
vizP <- function(eff = 1,
                 n = 10,
                 s = 1,
                 N = 15,
                 alfa = 0.05,
                 M = 5000,
                 out = TRUE
){
   set.seed(19790424)
   pow <- rep(NA,M); for(k in 1:M) pow[k] <- if(t.test(rnorm(n,eff,s))$p.value<0.05) 1 else 0
   POW <- mean(pow); POW
   M <- matrix(rnorm(n*N,mean=eff,sd=s), nrow=N, ncol=n)
   rownames(M) <- sprintf("sample %d", 1:N)
   colnames(M) <- sprintf("observation %d", 1:n)
   a <- min(M)
   b <- max(M)
   ci_ <- 0.5
   tsc <- 1.3
   if(out) x11(height=7, width=11)
   par(mar=c(1,1,1,1))
   plot(1,1,type='n',xlab="", ylab="",main="",yaxt='n',xaxt='n',bty='n',
        xlim=c(min(0,a),max(b,eff+2.5*s)), ylim=c(0.5,(N+5)))
   abline(h=N+ci_, lwd=2) # x-axis
   abline(v=0, lwd=2) # y-axis
   axis(side=1,at=c(0,eff),pos=N+ci_, hadj=-1, padj=-3.2, cex=tsc) # x-axis ticks
   abline(v=eff, lty=2, lwd=1, col="lightgray")
   ref <- dnorm(eff,eff,s)
   curve( 3*dnorm(x,eff,s)/ref+N+ci_, from=-10,to=10, add=TRUE, col="blue")
   text(x=eff+0.5*s, y=N+2*ci_+3*dnorm(eff+0.5*s,eff,s)/ref, paste("Pop. sd =", round(s,1)), cex=tsc, pos=4)
   text(x=eff+1.0*s, y=N+2*ci_+3*dnorm(eff+1.0*s,eff,s)/ref, paste("Sample size =", n), cex=tsc, pos=4)
   text(x=eff+1.5*s, y=N+2*ci_+3*dnorm(eff+1.5*s,eff,s)/ref, paste("Power =", round(POW,2)), cex=tsc, pos=4)
   arrows( x0=0, x1=eff, y0=N+5, y1=N+5, code=3,length = 0.15, angle = 25 )
   text(x=0+eff/2, y=N+4, pos=3, "Effect", cex=tsc)
   k <- 1
   for(k in 1:N){
      tmp <- M[k,]
      points(x=tmp,y=rep(k,n), pch=k, col="blue")
      ci <- t.test(tmp, conf.level=(1-alfa))$conf.int
      COL <- if( min(ci)<= 0 ) "red" else "green"
      arrows(x0=ci[1], x1=ci[2], y0=k-ci_,y1=k-ci_, code=3,length = 0.15, angle = 25,col=COL)
      points(x=mean(tmp), y=k-ci_, pch=k, col=COL, cex=1.2)
      rm(tmp, COL)
   }
}
@
\frame{ % -------------------------------------------------------------------->
\frametitle{How to make 'null' results meaningful}

Generally, it '$H_0$ not rejected' is uninformative
\emph{unless} we know that the study had a good chance
of detecting an effect that is interesting.

\rymd E.g:  "Two methods of pain relief were compared. The
median difference of 4 on the VAS scale
was not statistically significant."

\rymd This would be enhanced by;

\rymd "The study was designed to have a 90\% chance of
detecting a clinically significant difference
of 9".
}
\frame{ % -------------------------------------------------------------------->
\frametitle{Attempt to visualize the power of a test}
Suppose we measure the effect of a drug
that on average does decrease the blood pressure
by a clinically significant amount (defined as 1 unit).

\rymd We measure the blood pressure on $n$ indivuals
before and after taking the drug.

\rymd Our data consist of $n$ 'indivual effects'
(before - after) which are positive if
the drug works. We assume these are Normal
with a standard deviation of 1 unit.

\rymd $H_0:$"average effect $= 0$" is determinded
by creating a 95\% confidence interval for
the mean effect.
}
\frame{ % -------------------------------------------------------------------->
\frametitle{A sample size of 5}
<<n5>>=
vizP(n=5, out=FALSE)
@
}
\frame{ % -------------------------------------------------------------------->
\frametitle{A sample size of 10}
<<n10>>=
vizP(n=10, out=FALSE)
@
}
\frame{ % -------------------------------------------------------------------->
\frametitle{A sample size of 25}
<<n25>>=
vizP(n=25, out=FALSE)
@
}
\frame{ % -------------------------------------------------------------------->
\frametitle{Power}
The power of a test is the probability
of rejecting the null hypothesis.

The power depends on
\begin{itemize}
\item effect size
\item sample size
\item the spread of the data
\item (the statistical test, significance level, etc.)
\end{itemize}

Some points
\begin{itemize}
\item In an experimental setting, you can control the sample size.
\item We usually express the power as a function of effect size.
\item We usually want high power ($\geq 80\%$) at some minimally
interesting effect size.
\item Calculations are generally gruesome.
\end{itemize}
}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section[Power]{Examples} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



\frame{ % -------------------------------------------------------------------->
Idea: Breastfeeding example.
<<eval=FALSE, include=FALSE, >>=
library(reshape2)
library(ggplot2)

load("data/F4_breastfeeding.Rdata")
hist(x, breaks=seq(0,200,25))
hist(y, breaks=seq(0,200,25))
df <- model.frame(~x+y)
df$id <- 1:dim(df)[1]

mdf <- melt(df, id.vars = "id")
ggplot(mdf, aes(value)) + geom_histogram(binwidth=15) + facet_wrap(~variable)

df$diff <- with(df, y-x)
hist(df$diff)

N  <- length(x)


load("data/F4_breastfeeding.Rdata")
diffy <- y - x

p_boot <- function(m, bi=50){
   # m = sample size, bi = bootstrap iterations, mi = meta iterations
   P <- rep(NA_real_, bi)
   for(indx in 1:bi){
      boot_sample <- sample(x = diffy, size = m, replace = T)
      P[indx] <- wilcox.test(boot_sample, exact = FALSE)$p.value
   }
   P
}
x11(); hist(p_boot(14))

pow_boot <- function(m, bi=50, mi=50, thresh=0.05, probs=c(0.05,0.5,.95)){
   p_ge_thresh <- rep(NA_real_, mi)
   for(indx in 1:mi){
      p_tmp <- p_boot(m, bi)
      p_ge_thresh[indx] <- sum(p_tmp<0.05)/bi
   }
   M <- quantile(p_ge_thresh, probs = probs)
   names(M) <- paste0(100*probs, "%")
   M
}
pow_boot(14, 100, 100)

search <- function(m, bi=50, mi=50, thresh=0.05, probs=c(0.05,0.5,.95)){
   m_n <- length(m)
   M <- matrix(NA_real_, nrow=m_n, ncol=3)
   colnames(M) <- paste0(100*probs, "%")
   rownames(M) <- m
   for(indx in 1:m_n){
      cat("progress: ", indx, "of", m_n, "\n")
      M[indx,] <- pow_boot(m[indx], bi, mi, thresh, probs)
   }
   as.data.frame(M)
}
(POW1 <- search(m=c(10,15,20,25,30,35,40,45), bi = 100, mi = 100))
(POW2 <- search(m=c(10,15,20,25,30,35,40,45), bi = 250, mi = 100))
(POW3 <- search(m=c(10,15,20,25,30,35,40,45), bi = 500, mi = 200))
save(list=sprintf("POW%d",1:3), file="data/power_bm.rdat")
@
}
\frame{ % -------------------------------------------------------------------->
\frametitle{Sample size calculations without a model}
Recall the breastfeeding example from lecture 4.
{\tiny
<<echo=FALSE, include=TRUE, results='asis', cache=FALSE>>=
load("data/F4_breastfeeding.Rdata")
bord <- rbind(y,x,y-x,c(NA, rank(abs(y-x)[-1])))
colnames(bord) <- 1:14
rownames(bord) <- c("breast", "bottle", "diff", "rank")
latex(bord,file="", title="pair")
@
}
<<echo=FALSE, include=TRUE, results='asis'>>=
neg <- bord[4,bord[3,]<0]
pos <- bord[4,bord[3,]>0]
df <- data.frame(
    part = c("negative", "positive"),
    rank = c(paste0(neg, collapse=", "), paste0(pos, collapse=", ")),
    sum = c(sum(neg), sum(pos))
)
latex(df,file="",rowname=NULL)
@



}

\frame{ % -------------------------------------------------------------------->
Idea: New drug versus Dabigatran.
}
\frame{ % -------------------------------------------------------------------->
Hoo
}
\frame{ % -------------------------------------------------------------------->
\frametitle{References}
\begin{itemize}
   \item Chapters 23-25: Petrie \& Sabin. \emph{Medical Statistics at a Glance}, Wiley-Blackwell (2009).
\end{itemize}
}
\end{document} % <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
